### PR TITLE
LISA-2306: Work on upgrade to play 2.6

### PR DESCRIPTION
**Pull request by drewmiley**

### CODE REVIEW

**Comment by chrisjameswright** [comment]
Generally, I think this is in a state where it could be merged. However, I would suggest there are a couple of warnings that are now produced that we should fix beforehand:

1. `Logger configuration in conf files is deprecated and has no effect. Use a logback configuration file instead.`
2. `application.router is deprecated, use play.http.router instead`
3. `play.crypto.secret is deprecated, use play.http.secret.key instead`
4. `application.router is deprecated, use play.http.router instead`
5. `application.langs is deprecated, use play.i18n.langs instead`

**Comment by drewmiley** [comment]
Thanks for having a look- I'll see what i can do.

**Comment by drewmiley** [comment]
I've addressed points 2-5. I may need a little help on the creating the logback file.

**Comment by chrisjameswright** [comment]
Point 1 seems to be addressed now, having removed the logging related lines from application.conf

**Pull request merged**
